### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by pdesaulniers**
Meant to fix https://github.com/teal-language/teal-types/issues/7. I don't have sufficient rights on Travis to actually test this :)

### CODE REVIEW

**Comment by hishamhm** [comment]
@pdesaulniers I have enabled Travis CI for the teal-language org (I think Github has two styles of integration, not sure if this is the same that was enabled for the tl repo — at least right now it's not showing that CI is not set up anymore, but it didn't auto-trigger a build)

**Comment by hishamhm** [comment]
Maybe try pushing something to this PR to see if it triggers now?

**Comment by pdesaulniers** [comment]
Well, the build passes, but the script doesn't work at all...

**Comment by pdesaulniers** [comment]
OK, it now fails, which is the expected behavior. (The CI branch is missing some fixes from master)

**Comment by hishamhm** [comment]
> Do you think we should run these tests for both the latest tl stable release and the latest tl from git?

Good question. I think so? It would be good to know ahead of a release if something breaks the modules (especially if combined with the trigger-travis script).

I can push the `dev` rockspec to luarocks.org to make it easier.

Also, I think we can get away with only running tests here on Lua 5.3 and LuaJIT 2.1. The compiler itself is tested in the other repo, after all — running two versions here is already a sanity check in case of lack of test coverage in the main test suite.

**Comment by pdesaulniers** [comment]
OK, done.

One last thing we could do is add the `--quiet` flag to `tl` (or simply redirect stdout to /dev/null), but I think it can wait.

**Comment by hishamhm** [comment]
Merged!!

**Pull request merged**
