### PR TITLE
Neovim: change how types are autogenerated

### PR DESCRIPTION
**Pull request by euclidianAce**
Neovim is slowly starting to expose more of its api type info to lua so
we can generate more types. Generating these all in separate files is
annoying to require them all in manually (and if someone is looking to
cause trouble, could be required in without the type checker
complianing), so now this uses a 'template' file to just copy paste the
types in.

### CODE REVIEW

**Comment by hishamhm** [comment]
I know nothing about neovim, and I don't know if anyone else around is able to review this. In this case, I'd just go ahead and merge it, and if someone else spots any problems, then we can address them if they come up.

**Comment by euclidianAce** [comment]
The most I can really say is that they've been working well for me, I know of some people that want to use teal for some neovim stuff, but the lack of type inheritance/composition is holding back the annotations for [luv](https://github.com/luvit/luv) which is what neovim uses for its async stuff, and has a bunch of type inheritance. So until then, I don't know of anyone else using these :P

**Comment by hishamhm** [comment]
> the lack of type inheritance/composition is holding back the annotations for luv

would adding interfaces address this?

**Comment by euclidianAce** [comment]
I think so, if you want to see the types themselves they're actually pretty well documented [here](https://github.com/luvit/luv/blob/master/docs.md#contents), basically if everything indented after `uv_handle_t` would implement the same interface I believe that would work

**Pull request merged**
