### PR TITLE
Add declaration file for json.lua

### PR DESCRIPTION
**Pull request by pdesaulniers**
Here's a very simple declaration file for [json.lua](https://github.com/rxi/json.lua), just in case you needed an example :)

An old version of the library can be found on [LuaRocks](https://luarocks.org/modules/djfdyuruiry/rxi-json-lua).

TODO:
- ~~Add proper tests for the declaration file using busted~~ (ideally, we should also be able to run `busted` at the root of the project to test all the declarations in the repo)
- Add a .rockspec file so that the declaration can be installed using `luarocks install @types/rxi-json-lua` or something similar (not sure if LuaRocks would allow that name...)

### CODE REVIEW

**Comment by hishamhm** [comment]
I've been slow to merge this because I've been thinking about how to organize modules here:

> ideally, we should also be able to run busted at the root of the project to test all the declarations in the repo

I'm wondering if we should be using busted for testing the type declarations. The busted tests end up being more verbose than the type definitions themselves. Plus, this kind of unit tests don't really verify that the types match what the Lua modules actually do, and they mostly re-state what's being said in the `.d.tl` file. I'm thinking maybe something lighterweight such as just running `tl check` on the `.d.tl` file to verify that it is syntactically correct? 

> Add a .rockspec file so that the declaration can be installed using luarocks install @types/rxi-json-lua or something similar (not sure if LuaRocks would allow that name...)

`types/rxi-json-lua` would be valid if we created a `types` account, but we can figure that out later.

**Comment by pdesaulniers** [comment]
> I'm thinking maybe something lighterweight such as just running tl check on the .d.tl file to verify that it is syntactically correct?

Yeah, that would be good enough for this library.

> this kind of unit tests don't really verify that the types match what the Lua modules actually do, and they mostly re-state what's being said in the .d.tl file

I agree, this approach is not so great, but I figured it was better than nothing. I considered adding tests because some libraries can be pretty hard to type, and I wanted to make sure that every kind of function call in these libraries worked as intended.

In some cases, I guess we *could* verify that the types match what the Lua modules actually do, but that wouldn't be very practical. We'd have to download tons of libraries and programs each time we run the tests from scratch :)

**Comment by hishamhm** [comment]
I was just about to merge this (with the Busted tests removed), but I noticed another small issue to settle first: naming. 

To avoid conflicts, I think we should go with the package directories _as used in the root manifest repository of LuaRocks_ — `rxi-json-lua` in this case, even though apparently that wasn't uploaded into LuaRocks by the original author (I can switch ownership to the original author if they are interested).

@pdesaulniers Sounds good? 

PS: I added a comment at the json.lua repo: https://github.com/rxi/json.lua/issues/13#issuecomment-615307035

**Comment by pdesaulniers** [comment]
@hishamhm Yes, that makes sense.

**Comment by hishamhm** [comment]
Cool! Merged manually! We can address CI for `tl check`ing the modules and rockspecs later.

**Pull request closed without merging**
