### PR TITLE
Add support for Penlight

### PR DESCRIPTION
**Pull request by wqferr**
As stated in issue #19, [Penlight](https://github.com/lunarmodules/Penlight) is a "batteries"-type module for Lua, and I feel like teal would greatly benefit from integrating properly with it.

This pull request aims to add type declarations for most, if not all, features of Penlight.

I have never done work on a `.d.tl` file before, so I'm not sure how to debug or make sure everything is actually working. I'm creating this as a draft pull request to seek a bit of guidance and feedback while working on this.

### CODE REVIEW

**Comment by wqferr** [comment]
OK, so we might have a problem...

The Map type in Penlight just doesn't have a constructor. You either have to set the metatable directly OR you call the record itself.

As I understand it, Teal doesn't yet fully support metatables or anything related to it, so I can't just set the `__call` field somewhere, can I?

Any ideas of how I could proceed? Do I just postpone the Map record declaration until Teal supports metatables?

**Comment by wqferr** [comment]
Possible solution to the "Map has no constructor" problem:

Rename the type `Map` to `Map_`, and declare `Map` to be the function that returns a new instance of that record.

This could lead to confusion for someone who just wants to declare a variable as a `pl.Map`. Declaring it as `pl.Map_` would not be the first thing that crossed my mind if I saw an error at the declaration.

If this is the way to go, though, I think it'd be best to do the same for `List`, since even though it has a constructor, the documentation and examples use the `List {1, 2, 3}` notation very frequently.

I'm going to tag @hishamhm since you haven't responded to my previous message, but please tell me if I should avoid doing that.

**Comment by hishamhm** [comment]
Thanks for the ping, no worries!

Yeah, the lack of `__call` is probably the most annoying problem with the lacking metatable support right now. Still haven't figured out what's the cleanest way to support this, but we'll get there eventually!

> This could lead to confusion for someone who just wants to declare a variable as a pl.Map. Declaring it as pl.Map_ would not be the first thing that crossed my mind if I saw an error at the declaration.

This idea of declaring separate types is interesting! Just checking first if there might be side-effects of presenting `pl.Map` as a function only: do `pl.Map` and `pl.List` also any have fields that need to be accessed directly (as in `pl.Map.foo`), other than calling them as a function?

Now that you gave this suggestion of declaring a separate type, one brave suggestion would be to create a new module, `pl.types`, and put the data structure types `pl.types.Map` and `pl.types.List` in there. This approach could produce nicer looking error messages with the types being called `Map` and `List`, with locations pointing to their proper definitions, and definition files can require the `pl.types` module and do things such as `local Map = require("pl.types").Map` as shorthands (note the use of `local` instead of `local type` because of a [current issue](https://github.com/teal-language/tl/issues/269)).

How does that sound? :thinking:

**Comment by wqferr** [comment]
>Do pl.Map and pl.List also any have fields that need to be accessed directly (as in pl.Map.foo), other than calling them as a function?

As in the types? Akin to static methods? List does have `iterate`, which creates a list from a sequence and iterates over it, `split` which splits a string into substrings, and `range` which behaves like python's `range`. List does have the `new` method though, so we could just do this little workaround for `Map` while we don't have proper metatable support in Teal.

`MultiMap` seems to work the same way as `Map`, so no further problem there.

`Date` apparently has a constructor with the same name, so I'm not sure which pattern it follows.

Other than that, it does sound good, but I think `local Map = require("pl.types").Map` would clash with `local Map = require("pl.Map")`, which is what I would personally use. Two different things being imported into the same name by different people could lead to confusion when reading third party code. (I just realized you said that specifically about definition files, but I spent way too long typing this out and maybe you can take something out of it).

So just to be sure, this is how an example script could create a Map with an explicit variable declaration:

```lua
local pl = require("pl")
local Map = require("pl.Map") -- or local Map = pl.Map

local m: pl.types.Map<number, string> -- I think I like it better with the fully qualified name here

-- stuff

m = Map<number, string> {[10] = "ten", [20] = "twenty"}

-- use map
```

**Comment by wqferr** [comment]
Update on the current situation: most of the modules are mapped, but there are a few points of doubt which I've marked with TODO or FIXME. A few submodules are still unmapped mostly due to my procrastination.

I will mark the points of doubt for discussion on the pull request soon.

**Comment by hishamhm** [comment]
@wqferr I think if you `git rebase master` now, it should run green!

**Comment by wqferr** [comment]
Never used rebase before, can `git rebase master` like that fail? Is the branch structure ok as it is?

**Comment by hishamhm** [comment]
@wqferr it won't fail, since there are no conflicting files. 

Also, if anything ever goes wrong in git, `git reflog` is your best friend: it gives you essentially an "undo history" of your repository, with SHA hashes of every point in time. If you want to go back to a previous state, you can always `git reset --hard <old-hash>`. 

And if you want to avoid the thrill of resetting, you can always create a local branch copy before running experiments:

```bash
# go to master
git checkout master
# resync it
git pull
# go to your branch
git checkout wqferr-penlight
# create a new branch that's a copy of it
git branch -B copy-of-my-branch
# now try the rebase
git rebase master
# everything alright? go back:
git checkout wqferr-penlight
# now either do "git rebase master" again, or "git reset --hard copy-of-my-branch": it will produce the same end result
git rebase master
# all good, push!
git push
```

My other git tip is to use `gitk`, if you're on Linux. It's an old, uglyish program, but it displays a graphical tree view of the history and it's very good at that (even with crazier git trees). I often run `gitk` from the terminal in between git commands just to get a quick graphical view of what's going on, then close it and go back to the terminal for the next command. (Also, if you don't have it already, configuring your shell prompt to show git status automatically is another huge productivity boost.)

**Comment by wqferr** [comment]
Don't I need to force push? Since rebasing is technically rewriting history?

**Comment by hishamhm** [comment]
@wqferr Yes, but since this wasn't merged yet, rewriting history of the PR itself is ok

**Comment by hishamhm** [comment]
@wqferr Hey! We ended up never merging this! The tests ran green, so how about we merge it (even if there are still TODOs) so that people can start using it and maybe help to fill any gaps that may still be there?

**Comment by hishamhm** [comment]
btw, apparently there's a file called `).d.tl` ?

**Comment by wqferr** [comment]
I'm sorry for vanishing these past couple weeks, I've been a wreck lately and literally just broke up. I'm not sure I'll be able to work on this project any time soon. I wish Teal a very long and healthy development, and I'm sad I can't be a part of it for now.

**Comment by hishamhm** [comment]
@wqferr Don't worry! I'll take care of this. Take your time, and take good care of yourself! We'll be around when you feel like joining anytime!

**Comment by hishamhm** [comment]
I removed the stray file and merged this PR manually!

This is a huge contribution! Cheers!

**Pull request closed without merging**
