### PR TITLE
Add (mvp) Love2D type definitions

### PR DESCRIPTION
**Pull request by Fang-**
Draft PR because this isn't particularly usable as-is.

This file was auto-generated using [a little script I wrote](https://github.com/love2d-community/love-api/compare/fcb338f...Fang-:generate-d.tl), which uses the [love-api library](https://github.com/love2d-community/love-api) to generate teal type definitions. It depends on love2d-community/love-api#93 and love2d-community/love-api#94, and even then isn't good enough for production...

- Even if table definitions are available, it skips past those, and just defines the type as `table` instead.

- It doesn't handle variadic functions well at all. The love-api/wiki don't really help this, they're rather inconsistent in how they define such cases.

- It doesn't account for the supertypes in type definitions.

Consider this an RFC. I'd like some help with taking this all the way. cc @pdesaulniers, who I've seen use love in his issues/examples before. Apologies if any of this should be obvious, my lua is rusty, and I've haven't used/seen much teal in production yet.

- How do I best restructure this to make the various types and enums defined herein available to the developer? This is really hard to use otherwise.

- Can we do inline/anonymous records somehow? Should we want to? A handful of functions take tables with specific shapes (aka records) as arguments, or return them, but do not have a "real" type definition in the API docs. Should we give them proper names anyway?

- Is there any way to implement inheritance? Most records herein inherit the functions from `Object`, and some from `Data`, but manually redeclaring the inherited functions seems rather crude.

- The tutorial briefly mentions a `userdata` type, which I believe is a native lua type, but the compiler considers it an unknown type. What's up with that?

- Would it be considered better style to include argument names in function definitions, or does it not matter?

- What should happen to the script used to generate this? Should we include it in this repository? It depends on love2d-community/love-api. Would we be fine with pulling in a git submodule?

Also, peculiarly, trying to build this gives three "unknown type" errors, even though they _are_ defined, and are used successfully elsewhere in the file. Compiler bug?

```
love.d.tl:858:37: unknown type Font.HintingMode
love.d.tl:860:29: unknown type Font.HintingMode
love.d.tl:945:24: unknown type Font.Rasterizer
```

### CODE REVIEW

**Comment by pdesaulniers** [comment]
FYI, there is already [a set of definitions for love2d](https://github.com/MikuAuahDark/love2d-tl). (We should really advertise this repo somewhere, or copy over the definitions to teal-types!)

> How do I best restructure this to make the various types and enums defined herein available to the developer? This is really hard to use otherwise.

At a glance, the structure seems fine. Types should be accessible through `love.somemodule.SomeType`. I suppose you're looking for some way to avoid specifying `love.somemodule` before the type?

> Is there any way to implement inheritance? Most records herein inherit the functions from Object, and some from Data, but manually redeclaring the inherited functions seems rather crude.

No, Teal does not support subtyping yet :/ However, I believe this is the next feature on @hishamhm's roadmap.

> Would it be considered better style to include argument names in function definitions, or does it not matter?

I think argument names should be included. That way, language servers will be able to produce better information about the function definitions.

> Also, peculiarly, trying to build this gives three "unknown type" errors, even though they are defined, and are used successfully elsewhere in the file. Compiler bug?

I think these definitions are referring to the `Graphics.Font` record, which shadows the other `Font` record. It is defined here: https://github.com/teal-language/teal-types/blob/1f428f9b917997d98f637583bc14fdda7700f535/types/love/love.d.tl#L559-L575

**Comment by pdesaulniers** [comment]
By the way, the `love` record should be global and preloaded using `tlconfig.lua`. That way, users won't have to specify `require('love')` in their code:
```lua
return {
	preload_modules = {
		"love"
	}
}
```

**Comment by Fang-** [comment]
> FYI, there is already a set of definitions for love2d.

Oh man, that looks like it has me beat! (^:  
It seems to be doing a lot of work to clean up the love-api definitions though. Might be a good idea to upstream those, to love-api and the wiki? Happy to help with that, if you think it makes sense to do so.

+1 to pushing love2d-tl harder, to avoid duplicating effort like this. Might just close this pr in favor of that, unless you think there's anything worth saving here.

> At a glance, the structure seems fine. Types should be accessible through `love.somemodule.SomeType`.

This actually gives me "unknown type" errors. But might be related to how I'm loading it in. Doing the `global` from `preload_modules` like you describe just gives me "unknown variable: love", so I guess I'd still have to dedicate code to applying the type? I'm probably missing something dumb.

Do you know of any examples of love2d-tl being used in the wild, that I could look at?

**Comment by pdesaulniers** [comment]
> Do you know of any examples of love2d-tl being used in the wild, that I could look at?

Sorry, I'm not aware of any 'real' example yet :/ [This issue](https://github.com/MikuAuahDark/love2d-tl/issues/2) shows a small snippet.

> Doing the global from preload_modules like you describe just gives me "unknown variable: love"

You also need to change this line to `global record love` (with a lowercase letter). Otherwise, the `love` record won't be accessible in the global scope.

https://github.com/teal-language/teal-types/blob/1f428f9b917997d98f637583bc14fdda7700f535/types/love/love.d.tl#L2217

**Comment by MikuAuahDark** [comment]
> FYI, there is already a set of definitions for love2d. (We should really advertise this repo somewhere, or copy over the definitions to teal-types!)

I think my definition is quite stable already, except for a few blacklisted functions listed in the readme. While that's being said, it's fine to copy my `love.d.tl` over to this repository, but my concern is can someone guarantee that it's up-to-date, at least according to love-api definition?

**Comment by hishamhm** [comment]
@MikuAuahDark I can give you commit access to this repository, if you'd like to continue mantaining the love bindings here! Perhaps it would make it easier for discoverability?

**Comment by MikuAuahDark** [comment]
Sadly even myself can't guarantee that. I just updated my definition after I saw this issue.

**Comment by Fang-** [comment]
Gonna go ahead and close this, in any case. Thanks for your work, @MikuAuahDark. (:

**Pull request closed without merging**
